version: "1.0"
services:
   anon:
    build: .
    environment:
     API_HASH:   
     API_ID: 
     MONGO_URI: 
     BOT_TOKEN: 
     Inspector:
     Enforcer:
     DEVS:
     KAWAII_LOGS: 
     KAWAII_CHANNEL:

